import { Envelope } from "@domain/envelope"
import { ParticipantJoined, ParticipantLeft } from "@domain/built-in-envelopers"
import { ParticipantManifest } from "@domain/participant-manifest"
import { EnvelopeFactory } from "./envelope-factory"

export type NetworkRecord = {
	id: string
	name: string
	participantIds: string[]
}

export class Network {
	private readonly id: string
	private name: string
	private participantIds: string[]

	private constructor(id: string, name: string, participantIds: string[] = []) {
		this.id = id
		this.name = name
		this.participantIds = [...participantIds]
	}

	getId(): string {
		return this.id
	}

	getName(): string {
		return this.name
	}

	getParticipantIds(): string[] {
		return [...this.participantIds]
	}

	hasParticipant(participantId: string): boolean {
		return this.participantIds.includes(participantId)
	}

	connect(manifest: ParticipantManifest): ParticipantJoined {
		if (this.hasParticipant(manifest.id)) {
			throw new Error("Participant already connected")
		}

		this.participantIds.push(manifest.id)

		return EnvelopeFactory.participantJoined(this.id, manifest)
	}

	disconnect(participantId: string): ParticipantLeft {
		if (!this.hasParticipant(participantId)) {
			throw new Error("Participant not connected")
		}

		this.participantIds = this.participantIds.filter((id) => id !== participantId)

		return EnvelopeFactory.participantLeft(this.id, participantId)
	}

	validateEnvelope(envelope: Envelope): void {
		if (envelope.getNetworkId() !== this.id) {
			throw new Error("Envelope belongs to another network")
		}

		if (!this.hasParticipant(envelope.getSenderId())) {
			throw new Error("Sender not connected")
		}

		if (envelope.getType() === "participant.joined" || envelope.getType() === "participant.left") {
			throw new Error("Membership envelopes are generated by Network")
		}
	}

	toRecord(): NetworkRecord {
		return {
			id: this.id,
			name: this.name,
			participantIds: this.getParticipantIds(),
		}
	}

	static create(name: string): Network {
		return new Network(crypto.randomUUID(), name)
	}

	static rehydrate(record: NetworkRecord): Network {
		return new Network(record.id, record.name, record.participantIds)
	}
}
